// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240829143338_TestTeams")]
    partial class TestTeams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "aa097ec7-7811-459c-9509-34b14c555775",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "7d856cfd-72f1-4146-840a-7e459df65890",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "ead4feb7-cf8f-4d92-985b-22d9d0a9a7aa",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "97e0ae24-f7e2-4ad5-a1ee-570856fcf874",
                            RoleId = "aa097ec7-7811-459c-9509-34b14c555775"
                        },
                        new
                        {
                            UserId = "95fd4abd-0626-49fd-956c-19438402a603",
                            RoleId = "7d856cfd-72f1-4146-840a-7e459df65890"
                        },
                        new
                        {
                            UserId = "1f7ec708-e841-4ab2-846f-05c24fa18301",
                            RoleId = "7d856cfd-72f1-4146-840a-7e459df65890"
                        },
                        new
                        {
                            UserId = "e58ea87d-6a8f-49e0-939c-20d89f995574",
                            RoleId = "ead4feb7-cf8f-4d92-985b-22d9d0a9a7aa"
                        },
                        new
                        {
                            UserId = "f8d480c5-ebe1-45e3-a804-a9badf390003",
                            RoleId = "ead4feb7-cf8f-4d92-985b-22d9d0a9a7aa"
                        },
                        new
                        {
                            UserId = "c33ee900-c261-4195-b8d6-2ac802657d95",
                            RoleId = "ead4feb7-cf8f-4d92-985b-22d9d0a9a7aa"
                        },
                        new
                        {
                            UserId = "318f8ee8-cb12-4d95-9123-1d911a167f3f",
                            RoleId = "ead4feb7-cf8f-4d92-985b-22d9d0a9a7aa"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectManagement.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectManagement.Entities.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssigneeId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaskIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TasksDefinitions");
                });

            modelBuilder.Entity("ProjectManagement.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("241347d2-44a4-420c-8e0f-b27e8fdb8c1a"),
                            Name = "Team 1",
                            OwnerId = "1f7ec708-e841-4ab2-846f-05c24fa18301"
                        },
                        new
                        {
                            Id = new Guid("26f7c123-0749-4f53-892f-055d8e1fbcf0"),
                            Name = "Team 2",
                            OwnerId = "95fd4abd-0626-49fd-956c-19438402a603"
                        },
                        new
                        {
                            Id = new Guid("297f0f61-1ac0-4652-9423-4fb558209d6e"),
                            Name = "Team 3",
                            OwnerId = "95fd4abd-0626-49fd-956c-19438402a603"
                        });
                });

            modelBuilder.Entity("ProjectManagement.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "97e0ae24-f7e2-4ad5-a1ee-570856fcf874",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d04a081b-d181-4914-8c12-253f310d3279",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN1",
                            PasswordHash = "AQAAAAIAAYagAAAAEEL/FVOZxVi7i503mRP80d3VNozYYR5CUJ1Beqnsk7fPL/INDbF3G0Ntl5GBm2r+6w==",
                            PhoneNumberConfirmed = false,
                            Role = 0,
                            SecurityStamp = "57373b30-8f80-4fbc-9725-9436656c41fb",
                            TwoFactorEnabled = false,
                            UserName = "admin1"
                        },
                        new
                        {
                            Id = "95fd4abd-0626-49fd-956c-19438402a603",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f3edbd5-d5b8-40f2-96eb-5e42bf7f7ea3",
                            Email = "manager@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Manager",
                            LastName = "Manager",
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGER@GMAIL.COM",
                            NormalizedUserName = "MANAGER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEOum8XZi0YyxP3q7kkzyqGk/b1eEBQzHKMtNcwJzXUVqAISQP06ULTVTfUtNPtbXNQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "17b209ea-996d-464e-9335-ce134e0ec7a3",
                            TwoFactorEnabled = false,
                            UserName = "manager1"
                        },
                        new
                        {
                            Id = "1f7ec708-e841-4ab2-846f-05c24fa18301",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "caa8ab00-2a7f-4a90-8fe3-20008e61b164",
                            Email = "petar.topic@blankhq.co",
                            EmailConfirmed = true,
                            FirstName = "Manager2",
                            LastName = "Manager2",
                            LockoutEnabled = false,
                            NormalizedEmail = "PETAR.TOPIC@BLANKHQ.CO",
                            NormalizedUserName = "MANAGER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEIzRqHiFNB2VulEuLi8kLGLmqJsvXQnQL3ApzXTv9iGpywHXVaCmWALQIVBmcpb2rQ==",
                            PhoneNumberConfirmed = false,
                            Role = 1,
                            SecurityStamp = "b5a7518c-d89a-4710-b1d2-2366199a9a13",
                            TwoFactorEnabled = false,
                            UserName = "manager2"
                        },
                        new
                        {
                            Id = "e58ea87d-6a8f-49e0-939c-20d89f995574",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa0e4abf-f02c-475c-b6ca-9ca2cadc3575",
                            Email = "petartopic2002@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "User",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "PETARTOPIC2002@GMAIL.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAECeYnNYLTr7hTVbo0D9xm0wlLFys954lgq5h7XnstX79L+uAsOOLNT9c08tWdA1mzQ==",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "cd24f2f6-cd09-483c-96dc-702a2fbde0f4",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = "f8d480c5-ebe1-45e3-a804-a9badf390003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "86bc10e1-f6df-432e-a61e-8570cd9af764",
                            Email = "user2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "User2",
                            LastName = "User2",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@GMAIL.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEJF0FWeYwhXymkyjxIYGd5g4tLamz2WVK41mHvSuvX3HjIbcv42DAaLIkQsKAgY1aw==",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "1b3e5096-269a-4f6e-b53c-fd0644bb3ca0",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = "c33ee900-c261-4195-b8d6-2ac802657d95",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1028a2d7-cb0f-4f52-bd40-0951ba5f1f71",
                            Email = "user3@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "User3",
                            LastName = "User3",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@GMAIL.COM",
                            NormalizedUserName = "USER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEJir3uYIuTcrkgc5+4u3IvkjP3QE8jBcVkqqVoUlDbve3aT4l4RYN4i3oGx1YSu0gg==",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "afc2e8c8-f2ea-428c-83a8-f6797837bfe8",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = "318f8ee8-cb12-4d95-9123-1d911a167f3f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9e67c607-8eaf-449c-8bea-0a0c21d49b90",
                            Email = "user4@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "User4",
                            LastName = "User4",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@GMAIL.COM",
                            NormalizedUserName = "USER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEHs7nIcGupM2RZkzl/NxfgU4obURQf4mXMatX6FaWdurujFZdoAvtDM6YnfU5tBGMg==",
                            PhoneNumberConfirmed = false,
                            Role = 2,
                            SecurityStamp = "6a1a5e03-5fb4-493d-8fcd-c347e6a31214",
                            TwoFactorEnabled = false,
                            UserName = "user4"
                        });
                });

            modelBuilder.Entity("UserTeams", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectManagement.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectManagement.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectManagement.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Entities.Project", b =>
                {
                    b.HasOne("ProjectManagement.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ProjectManagement.Entities.TaskDefinition", b =>
                {
                    b.HasOne("ProjectManagement.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("ProjectManagement.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManagement.Entities.Team", b =>
                {
                    b.HasOne("ProjectManagement.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UserTeams", b =>
                {
                    b.HasOne("ProjectManagement.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
